In [1]:
from GetData.GetDataMultiDimensions import get_test_data, get_train_data
from GetData.GetDataOneDimension import getData
import numpy as np
import ot

In [46]:
def checkEven(x, y):
    rows_diff = x.shape[0] - y.shape[0]
    columns_diff = x.shape[1] - y.shape[1]

    if rows_diff > 0:
        zero_rows = np.zeros((rows_diff, y.shape[1]))
        y = np.vstack((y, zero_rows))
    elif rows_diff < 0:  
        zero_rows = np.zeros((-rows_diff, x.shape[1]))
        x = np.vstack((x, zero_rows))
    if columns_diff > 0: 
        zero_columns = np.zeros((y.shape[0], columns_diff))
        y = np.hstack((y, zero_columns))
    elif columns_diff < 0: 
        zero_columns = np.zeros((x.shape[0], -columns_diff))
        x = np.hstack((x, zero_columns))
    return x, y

In [48]:
def cost_matrix_aw(x, y):
    x, y = checkEven(x, y)
    x = np.array(x).reshape(np.array(x).shape[0], -1)
    y = np.array(y).reshape(np.array(y).shape[0], -1)
    C = ot.dist(x, y, metric="euclidean", p=2)
    return C

In [28]:
def cost_matrix_2d(x, y):
    m = len(x)
    n = len(y)
    Cxy = np.zeros((m, n))
    x1, y1 = 0, 0
    if x.shape[1] < y.shape[1]:
        zero_column = np.zeros((x.shape[0], y.shape[1] - x.shape[1]))
        x = np.hstack((x, zero_column))
    elif x.shape[1] > y.shape[1]:
        zero_column = np.zeros((y.shape[0], x.shape[1] - y.shape[1]))
        y = np.hstack((y, zero_column))
    return x, y, x.shape, y.shape

    # for row in range(m):
    #     for col in range(n):
    #         Cxy[row, col] = np.linalg.norm(x1[row] - y1[col])
    # return Cxy

In [27]:
X_train_BasicMotions, y_train_BasicMotions, X_test_BasicMotions, y_test_BasicMotions = getData("JapaneseVowels", '../Data/OneDimension/')
# for index, train in enumerate X_train_BasicMotions:
#     if train.shape != np.tuple(3, 206):
#         print(index, train.shape)
X_train_BasicMotions[0].shape[1], X_test_BasicMotions[0].shape

(20, (12, 19))

In [50]:
C = cost_matrix_aw(X_train_BasicMotions[50], X_test_BasicMotions[3])
C, C.shape

(array([[ 5.3540202 ,  3.17038942,  1.27990591,  3.14771495,  1.88597002,
          3.15328016,  2.64071245,  0.84071512,  2.17408872,  2.31937987,
          1.68971611,  1.47516142],
        [10.50606316,  2.67099103,  5.69266352,  3.38358275,  4.72924233,
          2.9330878 ,  2.96758624,  4.92577671,  3.43270719,  3.28224261,
          4.21885717,  4.44258924],
        [ 4.97578703,  3.76757989,  0.81344936,  2.64256516,  1.19642138,
          2.91459138,  3.00911143,  1.52719173,  2.45589838,  2.63697915,
          1.60701228,  1.45593812],
        [ 8.18423848,  2.54336716,  3.57059362,  1.13691262,  2.39259805,
          0.84443714,  1.82985285,  3.07499141,  1.9357621 ,  1.92691307,
          2.21965316,  2.43520463],
        [ 5.0700449 ,  3.87058097,  1.21457904,  2.68402239,  1.18695219,
          2.87494533,  2.99448162,  1.50830753,  2.51982469,  2.69926692,
          1.70923077,  1.53190289],
        [ 7.46594282,  1.32141243,  2.64980755,  1.41841237,  1.83996628,
      

In [19]:
from MaskingMap.MaskingMapLinear import (
    masking_map_linear_sub_sequence_multivariate
)

In [23]:
masking_map_linear_sub_sequence_multivariate(X_test_BasicMotions[0].T, X_train_BasicMotions[0].T, ratio=0.1, sub_ratio=0.1)

0.5538040057514182

In [3]:
import numpy as np
def subsequences(time_series, k):
    time_series = np.asarray(time_series)
    n = len(time_series)
    shape = (n - k + 1, k) + time_series.shape[1:]
    if time_series.ndim == 1:
        strides = time_series.strides * 2
    elif time_series.ndim == 2:
        strides = time_series.strides[0], time_series.strides[0], time_series.strides[1]
    return np.lib.stride_tricks.as_strided(time_series, shape=shape, strides=strides)

In [75]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
subsequences(a, 2)

array([[ 1,  2],
       [ 2,  3],
       [ 3,  4],
       [ 4,  5],
       [ 5,  6],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]])

In [76]:
b = np.array([[1,2], [2,3], [3,4], [4,5], [5,6], [6,7], [7,8], [8,9], [9,10]])
b.shape

(9, 2)

In [80]:
subs_xs = subsequences(b, 4)
subs_xs

array([[[ 1,  2],
        [ 2,  3],
        [ 3,  4],
        [ 4,  5]],

       [[ 2,  3],
        [ 3,  4],
        [ 4,  5],
        [ 5,  6]],

       [[ 3,  4],
        [ 4,  5],
        [ 5,  6],
        [ 6,  7]],

       [[ 4,  5],
        [ 5,  6],
        [ 6,  7],
        [ 7,  8]],

       [[ 5,  6],
        [ 6,  7],
        [ 7,  8],
        [ 8,  9]],

       [[ 6,  7],
        [ 7,  8],
        [ 8,  9],
        [ 9, 10]]])

In [40]:
import numpy as np

def split_into_subsequences_3d(data, shape):
    strides = data.strides
    shape = tuple(shape)
    strides = tuple(stride * shape[-1] for stride in strides) + strides
    return np.lib.stride_tricks.as_strided(data, shape=shape, strides=strides)


In [41]:

# Sử dụng hàm
data = np.arange(24).reshape((2, 3, 4))  # Một mảng 3 chiều (2x3x4)
subsequences = split_into_subsequences_3d(data, (2, 1, 2))  # Chia thành các chuỗi con (2x1x2)
print(data,subsequences)

ValueError: mismatch in length of strides and shape

In [15]:
subs_xs = subsequences(X_train_BasicMotions[1], 2)
subs_xs

ValueError: mismatch in length of strides and shape

In [ ]:
def masking_map_linear_sub_sequence(
    xs,
    xt,
    ratio=0.1,
    sub_ratio=0.1,
    eps=1e-10,
    reg=0.0001,
    max_iterations=100000,
    thres=1e-5,
    algorithm="linear_programming",
):
    sub_length = int(np.floor(min(len(xs), len(xt)) * sub_ratio))
    subs_xs = subsequences(xs, sub_length)
    subs_xt = subsequences(xt, sub_length)
    p = np.ones(len(subs_xs)) / len(subs_xs)
    q = np.ones(len(subs_xt)) / len(subs_xt)
    C = cost_matrix_aw(subs_xs, subs_xt)
    C /= C.max() + eps
    M = create_mask(C, ratio)
    if algorithm == "linear_programming":
        pi = lp(p, q, C, M)
    elif algorithm == "sinkhorn":
        pi = sinkhorn_log_domain(p, q, C, M, reg, max_iterations, thres)
    else:
        raise ValueError("algorithm must be 'linear_programming' or 'sinkhorn'!")
    cost = np.sum(pi * C)
    return cost

In [ ]:
from MaskingMap.MaskingMapLinear import masking_map_linear
from MaskingMap.knn import knn_masking_map_linear, knn_masking_map_auto_weighted_short, knn_masking_map_auto_weighted

In [ ]:
accuracy, time = knn_masking_map_linear(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, lamb=2)
print(accuracy, time)

100%|██████████| 30/30 [13:45<00:00, 27.53s/it]


0.82 826.0064129829407


In [ ]:
# with open('../Config/OneDimensionalDataset.txt', 'r') as file:
#     # [print(line.strip()) for line in file]
#     for line in file:
#         print(line.strip())

import json
with open('../Config/OneDimension.json', 'r') as file:
    data = json.load(file)
for data in data["masking_map_linear"]["parameters"]:
    print(data["k"])


1


In [ ]:
accuracy = knn_masking_map_auto_weighted(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test,ratio=0.2, lamb=3)
print(accuracy)

  0%|          | 0/30 [00:00<?, ?it/s]c:\Users\hoang\OneDrive\Documents\lab\AutoWeighted\venv\Lib\site-packages\cvxpy\reductions\solvers\solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)
100%|██████████| 30/30 [38:50<00:00, 77.68s/it]

0.7266666666666667


In [ ]:
accuracy = knn_masking_map_auto_weighted(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test,ratio=0.1, lamb=5)
print(accuracy)

  0%|          | 0/30 [00:00<?, ?it/s]c:\Users\hoang\OneDrive\Documents\lab\AutoWeighted\venv\Lib\site-packages\cvxpy\reductions\solvers\solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)
100%|██████████| 30/30 [36:43<00:00, 73.44s/it]

0.7333333333333333


In [ ]:
accuracy = knn_masking_map_auto_weighted(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test,ratio=0.2, lamb=3, algorithm="sinkhorn")
print(accuracy)

100%|██████████| 30/30 [4:59:53<00:00, 599.78s/it]  

0.74


In [ ]:
accuracy = knn_masking_map_auto_weighted(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test,ratio=0.1, lamb=5, algorithm="sinkhorn")
print(accuracy)

100%|██████████| 30/30 [3:25:51<00:00, 411.70s/it]  

0.7133333333333334


In [ ]:
accuracy = knn_masking_map_auto_weighted_short(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test,ratio=0.1, lamb=10)
print(accuracy)

c:\Users\hoang\OneDrive\Documents\lab\AutoWeighted\venv\Lib\site-packages\cvxpy\reductions\solvers\solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)


0.7933333333333333


In [ ]:
accuracy = knn_masking_map_auto_weighted_short(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test,ratio=0.1, lamb=20)
print(accuracy)

c:\Users\hoang\OneDrive\Documents\lab\AutoWeighted\venv\Lib\site-packages\cvxpy\reductions\solvers\solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)


0.7733333333333333


In [ ]:
accuracy = knn_masking_map_auto_weighted_short(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test,ratio=0.2, lamb=20)
print(accuracy)

c:\Users\hoang\OneDrive\Documents\lab\AutoWeighted\venv\Lib\site-packages\cvxpy\reductions\solvers\solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)


0.76


In [ ]:
accuracy = knn_masking_map_auto_weighted_short(X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test,ratio=0.3, lamb=10)
print(accuracy)

c:\Users\hoang\OneDrive\Documents\lab\AutoWeighted\venv\Lib\site-packages\cvxpy\reductions\solvers\solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)


0.7333333333333333


In [1]:
import numpy as np
import joblib
import sys
import os

In [2]:
X_train = joblib.load("../Data/MultiDimensions/MSRAction3D/X_train.pkl")
X_test = joblib.load('../Data/MultiDimensions/MSRAction3D/X_test.pkl')
y_train = joblib.load('../Data/MultiDimensions/MSRAction3D/y_train.pkl')
y_test = joblib.load('../Data/MultiDimensions/MSRAction3D/y_test.pkl')
np.array(X_train[0][1][1]).shape, X_test.shape, y_train.shape, y_test.shape

NameError: name 'joblib' is not defined

In [1]:
from GetData.GetDataMultiDimensions import getDataMultiVariate

In [2]:
X_train, y_train, X_test, y_test = getDataMultiVariate("SpokenArabicDigit")
X_train.shape, X_test.shape, y_train[0], y_test[0]

((6600,), (2200,), 0, 0)

In [3]:
from MaskingMap.MaskingMapLinear import masking_map_linear_sub_sequence_multivariate

In [4]:
masking_map_linear_sub_sequence_multivariate(X_train[1], X_test[0])

0.5053716202509346

In [7]:
len(X_test[0])

28

In [15]:
X_train, X_test, y_train, y_test = getDataMultiVariate("MSRDailyActivity3D")
X_train[0].shape, X_test[0].shape, y_train[0].shape, y_test[0].shape

((129, 60), (231, 60), (), ())

In [6]:
y_train[0]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [1]:
from MaskingMap.MaskingMapLinear import masking_map_linear_sub_sequence_multivariate
import numpy as np

In [10]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((160,), (160,), (160,), (160,))

In [11]:
np.array(X_train[0]).shape, np.array(X_test[0]).shape

((129, 60), (231, 60))

In [12]:
masking_map_linear_sub_sequence_multivariate(np.array(X_train[0]), np.array(X_test[0]))

0.9054941883018259

In [12]:
import os

# Hai chuỗi đường dẫn
folder_path = "Data/MultiDimensions/MSRAction3D/"
file_name = "X_train.pkl"

# Nối hai chuỗi đường dẫn để tạo đường dẫn tuyệt đối đến tệp
absolute_path = os.path.join(folder_path, file_name)

In [13]:
x = joblib.load(os.path.join(folder_path, file_name))
x.shape

(270,)

In [4]:
import numpy as np
import os
import joblib
directory = "Data/MultiDimensions/Weizmann/binary"

X = []
y = np.empty(80, dtype='<U9')

index = 0

for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f):
        X.append(joblib.load(f))
        y[index] = filename.split('_')[1]
        index = index + 1

In [1]:
from GetData.GetDataMultiDimensions import getDataMultiVariate

In [2]:
X_train, X_test, y_train, y_test = getDataMultiVariate("MSRAction3D")


In [3]:
X_train.shape, y_train.shape

((270,), (270,))

In [4]:
from MaskingMap.MaskingMapLinear import masking_map_linear_sub_sequence_multivariate

In [5]:
cost = masking_map_linear_sub_sequence_multivariate(X_train[0], X_test[0])
cost

0.6863258287069798

In [7]:
len(X_train[0])

54